server:
    port: 8080

spring:
    application:
        name: user-service
    
    datasource:
        url: jdbc:mariadb://localhost:3306/user_service_db?createDatabaseIfNotExist=true
        username: root
        password: 123456
        driver-class-name: org.mariadb.jdbc.Driver
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true

# Cấu hình Swagger/OpenAPI
# Cấu hình springdoc cho tài liệu OpenAPI (Swagger)
springdoc:
    api-docs:
        path: /v3/api-docs        # Thiết lập endpoint để truy cập JSON file mô tả API theo chuẩn OpenAPI (swagger.json)
    swagger-ui:
        path: /swagger-ui.html    # Endpoint để truy cập giao diện Swagger UI trực quan
        enabled: true             # Bật giao diện Swagger UI
        operations-sorter: method # Sắp xếp danh sách API trong UI mặc định theo HTTP method (GET, POST, ...)
        tags-sorter: alpha        # Sắp xếp các nhóm/tags API theo thứ tự alphabet
        display-request-duration: true  # Hiển thị thời gian thực thi request bên UI để thuận tiện theo dõi hiệu năng API
        csrf:
            enabled: false        # Tắt CSRF cho Swagger UI để tránh lỗi CORS